# ----- CLEO -----
# File: config.yaml
# Project: src
# Created Date: Tuesday 24th June 2025
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Tuesday 24th June 2025
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for example of using CLEO's python bindings.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py").
#

### Kokkos Initialization Parameters ###
kokkos_settings:
  num_threads: 16                                          # number of threads for host parallel backend

### SDM Runtime Parameters ###
domain:
  nspacedims: 0                                            # no. of spatial dimensions to model
  ngbxs: 1                                                 # total number of Gbxs
  maxnsupers: 64                                           # maximum number of SDs

timesteps:
  CONDTSTEP: 1                                             # time between SD condensation [s]
  COLLTSTEP: 1                                             # time between SD collision [s]
  MOTIONTSTEP: 1                                           # time between SDM motion [s]
  COUPLTSTEP: 1                                            # time between dynamic couplings [s]
  OBSTSTEP: 1000                                           # time between SDM observations [s]
  T_END: 240                                               # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ./build/_deps/cleo-src/libs/cleoconstants.hpp  # name of file for values of physical constants
  grid_filename : ./src/cleo_initial_conditions/0dparcel/dimlessGBxboundaries.dat  # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                         # type of initialisation of super-droplets
  initsupers_filename : ./src/cleo_initial_conditions/0dparcel/dimlessSDsinit.dat  # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename : ./build/bin/0dparcel_setup.txt     # .txt filename to copy configuration to
  zarrbasedir : ./build/bin/0dparcel_sol.zarr  # zarr store base directory
  maxchunk : 2500000                         # maximum no. of elements in chunks of zarr store array

### Microphysics Parameters ###
microphysics:
  condensation:
    do_alter_thermo: true                                  # true = cond/evap alters the thermodynamic state
    maxniters: 50                                          # maximum no. iterations of Newton Raphson Method
    MINSUBTSTEP: 0.001                                     # minimum subtimestep in cases of substepping [s]
    rtol: 0.0                                              # relative tolerance for implicit Euler integration
    atol: 0.01                                             # absolute tolerance for implicit Euler integration
